In [ ]:
import numpy as np
print(np.__version__) #버전
np.show_config() #구성

1.20.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']


# 모든 넘파이 경고를 무시하는 방법 - 권장되지 않음

In [ ]:
# 경고 무시
defaults = np.seterr(all = "ignore")
c = np.ones(1)/0

# 다시 돌아옴
_ = np.seterr(**defaults)

# equivalent with a context manager ???
with np.errstate(all = "ignore"):
    np.arrange(3)/0 

In [ ]:
z10 = np.zeros(10)
z10[4:8] = 1

z1010 = np.zeros((10,10))

print(z10)
print("=" * 50)
print(z1010) # 0이 10개가 10줄

[0. 0. 0. 0. 1. 1. 1. 1. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# 배열의 메모리 크기 찾기
print("z1010 = %d bytes" % (z1010.size* z1010.itemsize))
print(f"z10 = {z10.size* z10.itemsize} bytes")
print("8 byte each")

z1010 = 800 bytes
z10 = 80 bytes
8 byte each


# 값이 10~49인 벡터 

In [ ]:
n = np.arange(10,50)
print(n)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 벡터를 반전/뒤집기

In [ ]:
n = n[::-1]
print(n)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


# ( 0~8 범위의 값으로 ) 3*3 매트릭스 만들기 

In [ ]:
m = np.arange(9).reshape(3,3)
print(m)
m

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
matrix = np.eye(3)
print(matrix)
matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
rand_matrix = np.random.random((3,3,3))
print(rand_matrix)
rand_matrix

[[[0.51293642 0.30544371 0.8356006 ]
  [0.90830396 0.36059379 0.34858088]
  [0.02994605 0.67200308 0.52053728]]

 [[0.01910276 0.85831969 0.49205619]
  [0.38539556 0.05399784 0.98902942]
  [0.40001233 0.54311476 0.17751808]]

 [[0.26792137 0.69579648 0.56931558]
  [0.14889992 0.56523822 0.6022524 ]
  [0.67400097 0.8982407  0.5434153 ]]]


array([[[0.51293642, 0.30544371, 0.8356006 ],
        [0.90830396, 0.36059379, 0.34858088],
        [0.02994605, 0.67200308, 0.52053728]],

       [[0.01910276, 0.85831969, 0.49205619],
        [0.38539556, 0.05399784, 0.98902942],
        [0.40001233, 0.54311476, 0.17751808]],

       [[0.26792137, 0.69579648, 0.56931558],
        [0.14889992, 0.56523822, 0.6022524 ],
        [0.67400097, 0.8982407 , 0.5434153 ]]])

# 최소값 최대값 평균 찾기

In [ ]:
print(rand_matrix.min())
print(rand_matrix.max())
print(rand_matrix.mean())

0.019102760549430164
0.9890294229466134
0.49546567897272786


# 0이 아닌 요소 index(색인) 찾기

In [ ]:
nz = np.nonzero([1,2,0,5,6,0])
print(nz)
nz

(array([0, 1, 3, 4], dtype=int64),)


(array([0, 1, 3, 4], dtype=int64),)

# 경계가 1, 내부가 0 인 2차원 배열 VS 0인 테두리를 추가

In [ ]:
arr = np.ones((5,5))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
arr2 = np.ones((5,5))
arr2 = np.pad(arr2, pad_width = 1, mode = 'constant', constant_values = 0)
print(arr2)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
arr3 = np.ones((5,5))
arr3[:,[0, -1]] = 0
arr3[[0,-1], :] = 0
print(arr3)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


# np.nan

In [ ]:
0 * np.nan

nan

In [ ]:
np.nan - np.nan

nan

In [ ]:
np.nan == np.nan

False

In [ ]:
np.inf > np.nan

False

In [ ]:
np.nan in set([np.nan])

True

In [ ]:
0.3 == 3 *0.1 #???

False

# 대각선으로 매트릭스에 1~4 숫자 채우기

In [ ]:
ma = np.diag(1+np.arange(4), k=-1)
print(ma)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
# 8*8 매트릭스를 체크보드 패턴으로 채우기 

mat = np.zeros((8,8), dtype = int)
mat[1::2, ::2] = 1
mat[::2, 1::2] = 1
print(mat)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# 타일 함수로 체크보드 8*8 만들기

tile = np.tile(np.array([[0,1], [1,0]]), (4,4))
# 차곡 차곡 타일을 4개씩 놓기
print(tile)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# 100번째 원소의 색인(x, y, z) 은? - 형상 배열(6,7,8)을 고려하시오?
print(np.unravel_index(99, (6,7,8)))

(1, 5, 3)


In [ ]:
# 5*5 랜덤 행렬 정규화하기

five = np.random.random((5,5))
five = (five - np.mean(five))/np.std(five)
print(five)

[[ 0.82728678 -1.1027764   0.75111283  0.51842829 -1.3788252 ]
 [-1.04769445  0.35891095  0.25307908 -0.76168929 -1.30316303]
 [ 1.46493439  1.53716081  1.27150683  1.27110969 -0.57923676]
 [-0.76690424 -0.81292828 -1.30585602 -0.49614323  1.3713813 ]
 [-0.54871445  0.55007047  1.05588857 -1.3650079   0.23806926]]


In [ ]:
# 색상을 4 바이트 RGBA 로 나타내는 사용자 지정 dtype 생성

color = np.dtype([("r", np.ubyte, 1),
                 ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1),
                 ])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


C:\Users\user\AppData\Local\Temp/ipykernel_21996/1620885744.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


# np. dot == @ 

In [ ]:
np.ones((5,3)) # 1*1 + 1*1 + 1*1 = 3 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
a = np.dot(np.ones((5,3)), np.ones((3,2)))
print(a)

b = np.ones((5,3)) @ np.ones((3,2))
print(b) 

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


# 1차원 배열에 3과 8 사이의 모든 요소 부정하기

In [ ]:
c = np.arange(11)
c[(3<c) & (c<8)] *= -1
print(c)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [ ]:
print(sum(range(5), -1)) #?

9


In [ ]:
from numpy import * 
print(sum(range(5), -1))
# ?????

10


In [ ]:
np.array(0)/np.array(0)

C:\Users\user\AppData\Local\Temp/ipykernel_21996/1571972474.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0)/np.array(0)


nan

In [ ]:
np.array(0)//np.array(0)

C:\Users\user\AppData\Local\Temp/ipykernel_21996/3350367291.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0)//np.array(0)


0

In [ ]:
np.array([np.nan]).astype(int).astype(float) # e 지수인가?

array([-2.14748365e+09])

# 반올림 (?)

In [ ]:
# ? 
c = np.random.uniform(-10, +10, 10) 

np.copysign(np.ceil(np.abs(c)), c) 

array([ 8.,  5.,  1.,  2., -1., 10., -3.,  9.,  3.,  3.])

In [ ]:
# ??? 함수가 무슨 뜻?
# np.where(a, b, c)

# c가 0보다 크면, 올림처리 , 아니면 내림
np.where(c>0, np.ceil(c), np.floor(c))

array([ 8.,  5.,  1.,  2., -1., 10., -3.,  9.,  3.,  3.])

# 두 배열의 공통 값을 찾는법

In [ ]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(a)
print(b)
print(np.intersect1d(a,b))

[8 2 1 2 1 0 8 4 5 8]
[0 6 0 8 5 8 2 2 8 0]
[0 2 5 8]


In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1) # emath?

C:\Users\user\AppData\Local\Temp/ipykernel_21996/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [ ]:
yesterday = np.datetime64('today') - np.timedelta64(1) 
today = np.datetime64('today') 
tomorrow = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2022-03-10
2022-03-11
2022-03-12


In [ ]:
# 2022 년 3월에 해당하는 모든 날짜를 아는 방법
c = np.arange('2022-03', '2022-04', dtype = 'datetime64[D]')
print(c)

['2022-03-01' '2022-03-02' '2022-03-03' '2022-03-04' '2022-03-05'
 '2022-03-06' '2022-03-07' '2022-03-08' '2022-03-09' '2022-03-10'
 '2022-03-11' '2022-03-12' '2022-03-13' '2022-03-14' '2022-03-15'
 '2022-03-16' '2022-03-17' '2022-03-18' '2022-03-19' '2022-03-20'
 '2022-03-21' '2022-03-22' '2022-03-23' '2022-03-24' '2022-03-25'
 '2022-03-26' '2022-03-27' '2022-03-28' '2022-03-29' '2022-03-30'
 '2022-03-31']


# (A+B)*(-A/2) 제 자리에서 계산

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3

np.add(A,B, out= B)
np.divide(A,2, out = A)
np.negative(A, out=A)
np.multiply(A,B, out=A)

array([-1.5, -1.5, -1.5])

# 5가지 다른 방법으로 양수 배열의 정수 부분 추출하기

In [ ]:
c = np.random.uniform(0,10,10)

print(c - c%1)
print(c // 1)
print(np.floor(c))
print(c.astype(int))
print(np.trunc(c))

[4. 2. 7. 3. 7. 0. 2. 7. 6. 2.]
[4. 2. 7. 3. 7. 0. 2. 7. 6. 2.]
[4. 2. 7. 3. 7. 0. 2. 7. 6. 2.]
[4 2 7 3 7 0 2 7 6 2]
[4. 2. 7. 3. 7. 0. 2. 7. 6. 2.]


# 행 값이 0~4 인 5*5 매트릭스 만들기

In [ ]:
c = np.zeros((5,5))
c += np.arange(5)
print(c)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
# 10개의 정수를 생성하고 이를 사용해 배열을 만드는 함수 
def generate():
    for x in range(10):
        yield x

z = np.fromiter(generate(), dtype=float, count = -1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


# 크기 10의 벡터 만들기